### ISSUE TITLE
Header not scrolling correctly in next branch without jQuery

### ISSUE THREAD

**Issue by 6pac** [6pac/SlickGrid#761]
![HeaderIssue](https://user-images.githubusercontent.com/143957/236623425-c79dfb7c-cf09-4847-9bac-e5c0a6e4cab5.gif)

As per GIF, header row is not scrolling. In the current ```master``` it works, but not in ```next```. I've spent about half an hour looking, but can't find the issue. @ghiscoding  or @MarkoBL

**Comment by 6pac** [comment]
(note this issue was occurring before my recent ```$.each()``` fix push)

**Comment by ghiscoding** [comment]
good catch, I'll take a look and come up with a fix, it's probably related to the scroll event not propagating. 

As for the `$.each()`, I tried to find any of them with a return in `slick.grid` and there's only 6 of them and none seem to have a `return`. Do we need to check also for `.forEach`? I wonder if the `.forEach` works with `return` instead of `continue`, my guess would be that forEach requires a `return` since I think `continue` are reserved to `for` loops only

**Comment by ghiscoding** [comment]
fixed in commit [98aeb9b](https://github.com/6pac/SlickGrid/commit/98aeb9b9b19ca2972af214629c62efc20330b5a0), there a  header-row scroll missing. It should be ok for all other elements, but it would be nice to keep that in mind to make all other elements works too.

I'm nearly all done with Controls & Plugins, there's only the Pager (pagination) plugin left to do. I do however want to also review all the code that Marko added as `utils.template('<div>...</div>')` and I plan to replace them all with proper DOM element creation, because as it currently stands the `utils.template` uses `innerHTML` to create these elements and I don't like that, it's a lot less efficient compare to pure element creation (`document.create`) and also prone to possible XSS attack (remember the sanitize html saga...), so anyway I intend to replace them all with pure JS and that could also improve the grid performance.

![brave_2UybkkKAPK](https://user-images.githubusercontent.com/643976/236637627-a035e1bb-8acb-4674-bdce-c53dbc3a39a6.gif)

**Comment by ghiscoding** [comment]
Reopening since I fixed it for regular grid but it's also totally broken for frozen grids

![brave_XdUdNMaqOT](https://user-images.githubusercontent.com/643976/236652825-9d189bbf-51ae-44ef-94f9-785fcd5e1446.gif)

**Comment by ghiscoding** [comment]
fixed again by commit [2405fe6](https://github.com/6pac/SlickGrid/commit/2405fe62b970eb84e5f24f7f5fbcb3f7b3469c78)

![chrome_6X4E2bQajc](https://user-images.githubusercontent.com/643976/236654997-de29d95f-d9ee-469b-80ed-80fa94ae61f7.gif)

**Comment by ghiscoding** [comment]
I'm also done migrating all Controls & Plugins, so at this point it's just code cleaning and making sure everything works as expected. I still want to replace all these `utils.template('<div>...</div>')` that I mentioned in [previous comment ](https://github.com/6pac/SlickGrid/issues/761#issuecomment-1537185614) since these are using innerHTML and I want to replace with native code

**Comment by 6pac** [comment]
Awesome. Yep, element creation sounds much better. I'd be looking at the jQuery source to see what they do there.

FYI I went over slick.grid.js with a fine tooth comb for the ```.each()``` issue and committed direct to ```next```. This should all be good now. 
Yes, ```.foreach``` should use ```return```, and ```for (let i = 0; i < children.length; i++) {``` should use ```continue```.

While we're on a roll, #737 still appears to be a problem. Happy to look, but you just seem to be 'in the zone' right now, so I suspect what might take me several hours you may be able to do in 15 minutes.

**Comment by 6pac** [comment]
nb. some of the ```$.each``` were converted to ```.forEach()``` and some were converted to ```for()``` iterations. I went back to the ```master``` branch, looked for ```.each``` and then looked at what it had been converted to to make sure the paradigms were correct.

**Comment by ghiscoding** [comment]
> While we're on a roll, #737 still appears to be a problem. Happy to look, but you just seem to be 'in the zone' right now, so I suspect what might take me several hours you may be able to do in 15 minutes.

I think this one is cause by the bottom container not being entirely filled except when you start scrolling then it adds more slick rows, a potential fix would be trigger a scroll event at same position when frozen row is changed to bottom.

**Comment by 6pac** [comment]
Thanks, that helps a lot. Will see what I can do
